output_dir: /home/hans/neurout/maua-style
transfer_type: 'img_img'
input:
  content:
  style:
  init: content
  seed: 12274069
param:
  num_scales: 13
  image_sizes: 300,1500
  size_scaling: linear
  num_iterations: 500,50
  iter_scaling: power
  content_weight: 5
  style_weight: 50000
  style_blend_weights: False
  style_scale: 1.0
  tv_weight: 0.0001
  original_colors: False
  normalize_weights: False
  use_covariance: False
model:
  model_file: ../style-transfer/models/vgg19-d01eb7cb.pth
  disable_check: False
  pooling: max
  content_layers: relu4_2
  style_layers: relu1_1,relu2_1,relu3_1,relu4_1,relu5_1
  gpu: 1
  backend: cudnn
  cudnn_autotune: True
  multidevice_strategy: 7
optim:
  optimizer: lbfgs
  lbfgs_num_correction: 100
  learning_rate: 1
  print_iter: 0
  save_iter: 0
