output_dir: /home/hans/datasets/cyphis/recomb/
transfer_type: 'img_img'
pbar: False
input:
  content: random
  style:
  init: content
  seed: 12274069
param:
  num_scales: 13
  image_sizes: 300,1500
  size_scaling: linear
  num_iters: 50,250
  iter_scaling: power
  content_weight: 0
  style_weight: 50000
  style_blend_weights: False
  style_scale: 1.0
  tv_weight: 0.0001
  match_histograms: avg
  original_colors: False
  normalize_gradients: False
  normalize_weights: True
  use_covariance: False
model:
  model_file: ../style-transfer/models/vgg19-d01eb7cb.pth
  disable_check: False
  pooling: max
  content_layers: relu4_2
  style_layers: relu1_1,relu2_1,relu3_1,relu4_1,relu5_1
  gpu: 0
  backend: cudnn
  cudnn_autotune: True
  verbose: False
  multidevice_strategy: 7
optim:
  optimizer: lbfgs
  lbfgs_num_correction: 100
  lbfgs_tolerance_change: -1 #1e-5
  lbfgs_tolerance_grad: -1 #1e-7
  learning_rate: 1
  print_iter: -1
  save_iter: -1
