output_dir: /home/hans/neurout/maua-style
transfer_type: 'img_vid'
pbar: True
input:
  content: random
  style: 'examples/ground_truth_sea_2.gif'
  init: random
  seed: -1
param:
  num_scales: 3
  image_sizes: 256,1024
  size_scaling: power
  num_iterations: 300,100
  iter_scaling: power
  avg_frame_window: -1
  gram_frame_window: 9,9,9,4
  num_frames: 24
  content_weight: 0
  style_weight: 1
  video_style_factor: 10
  shift_factor: 0
  style_blend_weights: False
  style_scale: 1.0
  tv_weight: 0.0001
  match_histograms: avg
  temporal_smoothing: 0
  original_colors: False
  normalize_gradients: True
  normalize_weights: True
  use_covariance: False
model:
  model_file: ../style-transfer/models/vgg19-d01eb7cb.pth
  disable_check: False
  pooling: max
  content_layers: relu4_2
  style_layers: relu1_1,relu2_1,relu3_1,relu4_1,relu5_1
  gpu: 1
  backend: cudnn
  cudnn_autotune: True
  multidevice_strategy: 6
  verbose: False
optim:
  optimizer: lbfgs
  lbfgs_num_correction: 100
  lbfgs_tolerance_change: -1 #1e-5
  lbfgs_tolerance_grad: -1 #1e-7
  learning_rate: 1
  save_iter: 1000
ffmpeg:
  vcodec: hevc_nvenc
  c:v: hevc_nvenc
  preset: slow
  b:v: 20M
  fps: 18
