output_dir: /home/hans/neurout/maua-style
transfer_type: 'img_img'
input:
  content:
  style:
  init: content
  seed: -1
param:
  num_scales: 2
  image_sizes: 256,512,1024,2048,3072,4096,5000,6000
  size_scaling: linear
  num_iterations: 500,500,400,300,200,100,50,50
  iter_scaling: linear
  content_weight: 1
  style_weight: 100
  style_blend_weights: False
  style_scale: 1.0
  tv_weight: 0.0001
  original_colors: False
  normalize_weights: False
  normalize_gradients: True
  use_covariance: False
model:
  model_file: ../style-transfer/models/vgg19-d01eb7cb.pth
  disable_check: False
  pooling: max
  content_layers: relu4_2
  style_layers: relu1_1,relu2_1,relu3_1,relu4_1,relu5_1
  gpu: 0,1
  backend: cudnn
  cudnn_autotune: True
  multidevice_strategy: 5
  verbose: True
optim:
  optimizer: lbfgs
  lbfgs_num_correction: 100
  lbfgs_tolerance_change: -1 #1e-5
  lbfgs_tolerance_grad: -1 #1e-7
  learning_rate: 1
  save_iter: 0
  print_iter: 0
ffmpeg:
  vcodec: hevc_nvenc
  c:v: hevc_nvenc
  preset: slow
  b:v: 20M
  fps: 18